version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    command: gunicorn mdr.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    restart: always
    ports:
      - 1234:80
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/staticfiles/:/static/
  # mysql:
  #   image: mysql
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ${PWD}/mysql:/var/lib/mysql
  #   environment: 
  #     - MYSQL_ROOT_PASSWORD=mypassword
  #     - MYSQL_DATABASE=mdr
